export const mockOffer = {
	id: 1,
	name0: 'mock name',
	perex0: '',
	description0: '',
	price: '0.00',
	currency: '',
	old_price: 0,
	dph: 0,
	product_type: 'mock type',
	code: null,
	ean: null,
	manufacturer: null,
	setting: 0,
	action: 0,
	news: 0,
	topseller: 0,
	hp: 0,
	related: null,
	store: 0,
	availability: 0,
	priority: 0,
	timestamp: 'timestamp',
	uri0: '',
	quantity: 0,
	customer_id: 0,
	published: 0,
	region: '',
	district: '',
	country: '',
	city: '',
	postal: '',
	hide_reason: null,
	delete_reason: null,
	unit_id: 0,
	shipping_available: 0,
	pricing_type: '',
	sold: 0,
	expiration_date: 'timestamp',
	old_expiration_date: null,
	expiration_notification_sent_datetime: null,
	waste_category_id: null,
	language: '',
	total_view_count: 0,
};
